version: '2.4'
services:
  eventwatcher:
    container_name: eventwatcher
    image: ghcr.io/reuschelcgn/eventwatcher-standalone:main
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./Eventwatcher-Standalone/.env:/usr/src/app/.env
      - ./Eventwatcher-Standalone/logs/:/usr/src/app/logs
    security_opt:
      - no-new-privileges:true
    logging:
      driver: none
